kind: pipeline
name: packer


steps:
- name: build-ubuntu
  image: plugins/docker
  settings:
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    repo: harbor.horten.kommune.no/private/packer
    registry: harbor.horten.kommune.no

  commands:
     - packer build -force -only=vsphere-iso -var-file=variables.json -var-file=isovars.json ./linux/ubuntu/ubuntu2004.json
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
    VSPHERE_CLUSTER:
      from_secret: vsphere_cluster
    VSPHERE_DATASTORE:
      from_secret: vsphere_datastore
    VSPHERE_NETWORK:
      from_secret: vsphere_network

- name: build-windows-core-2019
  image: plugins/docker
  settings:
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    repo: harbor.horten.kommune.no/private/packer
    registry: harbor.horten.kommune.no
  settings:
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    repo: harbor.horten.kommune.no/private/packer
    registry: harbor.horten.kommune.no
  commands:
     - packer build -force -only=vsphere-iso -var-file=variables.json -var-file=isovars.json ./windows/2019/core.json
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
    VSPHERE_CLUSTER:
      from_secret: vsphere_cluster
    VSPHERE_DATASTORE:
      from_secret: vsphere_datastore
    VSPHERE_NETWORK:
      from_secret: vsphere_network

- name: build-windows-gui-2019
  image: plugins/docker
  settings:
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    repo: harbor.horten.kommune.no/private/packer
    registry: harbor.horten.kommune.no
  commands:
     - packer build -force -only=vsphere-iso -var-file=variables.json -var-file=isovars.json ./windows/2019/gui.json
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
    VSPHERE_CLUSTER:
      from_secret: vsphere_cluster
    VSPHERE_DATASTORE:
      from_secret: vsphere_datastore
    VSPHERE_NETWORK:
      from_secret: vsphere_network

- name: teams-webhook
  image: jdamata/drone-teams
  settings:
    webhook: 
      from_secret: WEBHOOK
  when: 
     status: 
     - success
     - failure
     